### PR TITLE
Add asciideck.app file

### PR DESCRIPTION
**Pull request by psyeugenic**
I want to add a `rebar.config` and a `.app.src` to be able to use it with rebar3. =)

Please advice if I haven't considered something.

### CODE REVIEW

**Comment by essen** [comment]
Add the .app not the .app.src, and don't put a custom rebar.config, generate it: `app:: rebar.config`

**Comment by psyeugenic** [comment]
Yeah, no, that rebar.config should definitely not be there.

How do you deal with version-numbers in a committed `.app` file vs. `PROJECT_VERSION` in the Makefile? And all the other fields. The committed file takes precedence?

**Comment by essen** [comment]
The Makefile rebuilds the .app every time. It only changes and must be committed again when files get added, the version changes and small things like this. I haven't put the .app file yet because the project is not stable, but on a stable project that file only changes with new versions.

**Comment by essen** [comment]
Actually let me do it, it says version 0.0.1 which doesn't make much sense, I'll set the version to 0.1.0 and commit the .app file at the same time.

**Comment by essen** [comment]
Done, thanks!

**Comment by psyeugenic** [comment]
Yeah I just committed what the Makefile generated. ^^
thanks!

**Comment by essen** [comment]
It was the right thing to do. :-)

**Pull request closed without merging**
